// Dados locais das categorias para uso offline e fallback
export const TOPICOS = [
  { id: 'construcao', nome: 'Construção e Reformas', emoji: '🏗️' },
  { id: 'eletrica', nome: 'Elétrica e Automação', emoji: '⚡' },
  { id: 'hidraulica', nome: 'Hidráulica e Gás', emoji: '🚿' },
  { id: 'pintura', nome: 'Pintura e Acabamento', emoji: '🎨' },
  { id: 'marcenaria', nome: 'Marcenaria e Mobiliário', emoji: '🪚' },
  { id: 'limpeza', nome: 'Limpeza e Conservação', emoji: '🧹' },
  { id: 'jardim', nome: 'Jardim e Área Externa', emoji: '🌿' },
  { id: 'automotivo', nome: 'Automotivo', emoji: '🚗' },
  { id: 'tecnologia', nome: 'Tecnologia e TI', emoji: '💻' },
  { id: 'saude', nome: 'Saúde e Bem-estar', emoji: '❤️' },
  { id: 'beleza', nome: 'Beleza e Estética', emoji: '💄' },
  { id: 'educacao', nome: 'Educação e Aulas', emoji: '📚' },
  { id: 'eventos', nome: 'Eventos e Entretenimento', emoji: '🎉' },
  { id: 'alimentacao', nome: 'Alimentação e Culinária', emoji: '🍳' },
  { id: 'transporte', nome: 'Transporte e Logística', emoji: '🚚' },
  { id: 'seguranca', nome: 'Segurança', emoji: '🔒' },
  { id: 'animais', nome: 'Pets e Animais', emoji: '🐾' },
  { id: 'juridico', nome: 'Jurídico e Financeiro', emoji: '⚖️' },
  { id: 'design', nome: 'Design e Criação', emoji: '🎨' },
  { id: 'moda', nome: 'Moda e Costura', emoji: '🧵' },
]

export const CATEGORIAS_POR_TOPICO = {
  construcao: [
    { id: 'pedreiro', nome: 'Pedreiro', emoji: '🧱' },
    { id: 'mestre_obras', nome: 'Mestre de Obras', emoji: '👷' },
    { id: 'azulejista', nome: 'Azulejista', emoji: '🪣' },
    { id: 'gesseiro', nome: 'Gesseiro', emoji: '🏠' },
    { id: 'rebocador', nome: 'Rebocador', emoji: '🧰' },
    { id: 'carpinteiro', nome: 'Carpinteiro', emoji: '🪵' },
    { id: 'telhador', nome: 'Telhador', emoji: '🏚️' },
    { id: 'impermeabilizador', nome: 'Impermeabilizador', emoji: '💧' },
    { id: 'drywall', nome: 'Drywall e Divisórias', emoji: '🧱' },
    { id: 'piscina', nome: 'Piscinas', emoji: '🏊' },
    { id: 'madeira_deck', nome: 'Deck de Madeira', emoji: '🪵' },
    { id: 'piso_vinilico', nome: 'Piso Vinílico e Laminado', emoji: '🟫' },
    { id: 'cobertura', nome: 'Coberturas e Pergolados', emoji: '⛺' },
    { id: 'porcelanato', nome: 'Porcelanato', emoji: '⬜' },
    { id: 'concreto', nome: 'Concretagem', emoji: '🏗️' },
  ],
  eletrica: [
    { id: 'eletricista', nome: 'Eletricista', emoji: '⚡' },
    { id: 'ar_condicionado', nome: 'Ar-condicionado', emoji: '❄️' },
    { id: 'automacao', nome: 'Automação Residencial', emoji: '🏠' },
    { id: 'cameras', nome: 'Câmeras de Segurança', emoji: '📷' },
    { id: 'painel_solar', nome: 'Painel Solar', emoji: '☀️' },
    { id: 'alarme', nome: 'Alarmes', emoji: '🚨' },
    { id: 'portao_eletrico', nome: 'Portão Elétrico', emoji: '🚪' },
    { id: 'cerca_eletrica', nome: 'Cerca Elétrica', emoji: '⚡' },
    { id: 'iluminacao', nome: 'Iluminação e LED', emoji: '💡' },
    { id: 'quadro_eletrico', nome: 'Quadro Elétrico', emoji: '⚡' },
  ],
  hidraulica: [
    { id: 'encanador', nome: 'Encanador', emoji: '🚿' },
    { id: 'desentupidor', nome: 'Desentupidor', emoji: '🪠' },
    { id: 'vazamento', nome: 'Conserto de Vazamento', emoji: '💧' },
    { id: 'aquecedor', nome: 'Aquecedor e Boiler', emoji: '🔥' },
    { id: 'gas', nome: 'Gás Natural e GLP', emoji: '🔥' },
    { id: 'fossa', nome: 'Fossa e Esgoto', emoji: '🕳️' },
    { id: 'caixa_agua', nome: 'Caixa d\'água', emoji: '💧' },
    { id: 'bomba_agua', nome: 'Bomba d\'água', emoji: '⛽' },
    { id: 'banheiro_reforma', nome: 'Reforma de Banheiro', emoji: '🚿' },
    { id: 'irrigacao', nome: 'Irrigação', emoji: '💦' },
  ],
  pintura: [
    { id: 'pintor', nome: 'Pintor', emoji: '🎨' },
    { id: 'textura', nome: 'Textura e Grafiato', emoji: '🎨' },
    { id: 'gesso_decorativo', nome: 'Gesso Decorativo', emoji: '✨' },
    { id: 'papel_parede', nome: 'Papel de Parede', emoji: '📋' },
    { id: 'pintura_predial', nome: 'Pintura Predial', emoji: '🏢' },
    { id: 'verniz', nome: 'Verniz e Tingimento', emoji: '🪵' },
    { id: 'massa_corrida', nome: 'Massa Corrida', emoji: '🪣' },
    { id: 'adesivo_decorativo', nome: 'Adesivo Decorativo', emoji: '✂️' },
  ],
  marcenaria: [
    { id: 'marceneiro', nome: 'Marceneiro', emoji: '🪚' },
    { id: 'moveis_planejados', nome: 'Móveis Planejados', emoji: '🛋️' },
    { id: 'cozinha_planejada', nome: 'Cozinha Planejada', emoji: '🍳' },
    { id: 'serralheiro', nome: 'Serralheiro', emoji: '🔩' },
    { id: 'vidraceiro', nome: 'Vidraceiro', emoji: '🪟' },
    { id: 'grades_ferro', nome: 'Grades e Portões', emoji: '⛓️' },
    { id: 'persiana', nome: 'Persianas e Cortinas', emoji: '🪟' },
    { id: 'solda', nome: 'Solda e Metalurgia', emoji: '🔩' },
    { id: 'closet', nome: 'Closet Planejado', emoji: '👗' },
    { id: 'box_banheiro', nome: 'Box de Banheiro', emoji: '🚿' },
  ],
  limpeza: [
    { id: 'diarista', nome: 'Diarista', emoji: '🧹' },
    { id: 'faxineira', nome: 'Faxineira', emoji: '🧽' },
    { id: 'limpeza_pos_obra', nome: 'Limpeza Pós-obra', emoji: '🏗️' },
    { id: 'dedetizador', nome: 'Dedetizador', emoji: '🐛' },
    { id: 'lavagem_sofa', nome: 'Lavagem de Sofá', emoji: '🛋️' },
    { id: 'lavagem_tapete', nome: 'Lavagem de Tapete', emoji: '🧺' },
    { id: 'higienizacao_ar', nome: 'Higienização de Ar', emoji: '❄️' },
    { id: 'limpeza_predial', nome: 'Limpeza Predial', emoji: '🏢' },
    { id: 'sanitizacao', nome: 'Sanitização', emoji: '🧪' },
    { id: 'controle_pragas', nome: 'Controle de Pragas', emoji: '🐜' },
  ],
  jardim: [
    { id: 'jardineiro', nome: 'Jardineiro', emoji: '🌿' },
    { id: 'paisagista', nome: 'Paisagista', emoji: '🌸' },
    { id: 'poda_arvore', nome: 'Poda de Árvores', emoji: '🌳' },
    { id: 'corte_grama', nome: 'Corte de Grama', emoji: '🌱' },
    { id: 'limpeza_terreno', nome: 'Limpeza de Terreno', emoji: '🌾' },
    { id: 'grama_sintetica', nome: 'Grama Sintética', emoji: '🏟️' },
    { id: 'piscina_manutencao', nome: 'Manutenção de Piscina', emoji: '🏊' },
  ],
  automotivo: [
    { id: 'mecanico', nome: 'Mecânico', emoji: '🔧' },
    { id: 'funileiro', nome: 'Funileiro', emoji: '🚘' },
    { id: 'eletrica_auto', nome: 'Elétrica Automotiva', emoji: '⚡' },
    { id: 'polimento', nome: 'Polimento e Vitrificação', emoji: '✨' },
    { id: 'higienizacao_auto', nome: 'Higienização Automotiva', emoji: '🧹' },
    { id: 'ar_auto', nome: 'Ar-condicionado Auto', emoji: '❄️' },
    { id: 'guincho', nome: 'Guincho e Reboque', emoji: '🚛' },
    { id: 'borracheiro', nome: 'Borracheiro', emoji: '🔧' },
    { id: 'lavagem_auto', nome: 'Lavagem Automotiva', emoji: '🚿' },
    { id: 'moto_mecanico', nome: 'Mecânico de Motos', emoji: '🏍️' },
  ],
  tecnologia: [
    { id: 'tecnico_informatica', nome: 'Técnico em Informática', emoji: '💻' },
    { id: 'formatacao', nome: 'Formatação e Manutenção', emoji: '🖥️' },
    { id: 'desenvolvimento_web', nome: 'Desenvolvimento Web', emoji: '🌐' },
    { id: 'design_grafico', nome: 'Design Gráfico', emoji: '🎨' },
    { id: 'marketing_digital', nome: 'Marketing Digital', emoji: '📱' },
    { id: 'fotografia', nome: 'Fotógrafo', emoji: '📷' },
    { id: 'edicao_video', nome: 'Edição de Vídeo', emoji: '🎬' },
    { id: 'drone', nome: 'Drone e Fotografia Aérea', emoji: '🚁' },
    { id: 'social_media', nome: 'Redes Sociais', emoji: '📸' },
    { id: 'rede_internet', nome: 'Rede e Internet', emoji: '🌐' },
  ],
  saude: [
    { id: 'personal_trainer', nome: 'Personal Trainer', emoji: '💪' },
    { id: 'nutricionista', nome: 'Nutricionista', emoji: '🥗' },
    { id: 'fisioterapeuta', nome: 'Fisioterapeuta', emoji: '🏥' },
    { id: 'massagista', nome: 'Massagista', emoji: '💆' },
    { id: 'enfermeiro', nome: 'Enfermeiro Domiciliar', emoji: '👩‍⚕️' },
    { id: 'cuidador_idoso', nome: 'Cuidador de Idoso', emoji: '👴' },
    { id: 'psicologo', nome: 'Psicólogo', emoji: '🧠' },
    { id: 'pilates', nome: 'Pilates', emoji: '🏋️' },
    { id: 'yoga', nome: 'Yoga e Meditação', emoji: '🧘' },
    { id: 'esteticista', nome: 'Esteticista', emoji: '✨' },
  ],
  beleza: [
    { id: 'cabeleireiro', nome: 'Cabeleireiro', emoji: '💈' },
    { id: 'barbeiro', nome: 'Barbeiro', emoji: '🪒' },
    { id: 'manicure', nome: 'Manicure e Pedicure', emoji: '💅' },
    { id: 'maquiadora', nome: 'Maquiadora', emoji: '💄' },
    { id: 'designer_sobrancelha', nome: 'Designer de Sobrancelha', emoji: '👁️' },
    { id: 'micropigmentacao', nome: 'Micropigmentação', emoji: '🎨' },
    { id: 'colorista', nome: 'Colorista', emoji: '🎨' },
    { id: 'depilacao', nome: 'Depilação', emoji: '✨' },
    { id: 'nail_designer', nome: 'Nail Designer', emoji: '💅' },
    { id: 'limpeza_pele', nome: 'Limpeza de Pele', emoji: '✨' },
  ],
  educacao: [
    { id: 'professor_particular', nome: 'Professor Particular', emoji: '📚' },
    { id: 'aula_ingles', nome: 'Aula de Inglês', emoji: '🇬🇧' },
    { id: 'aula_matematica', nome: 'Aula de Matemática', emoji: '➕' },
    { id: 'aula_musica', nome: 'Aula de Música', emoji: '🎵' },
    { id: 'aula_danca', nome: 'Aula de Dança', emoji: '💃' },
    { id: 'reforco_escolar', nome: 'Reforço Escolar', emoji: '📖' },
    { id: 'personal_coach', nome: 'Coaching e Mentoria', emoji: '🎯' },
    { id: 'aula_violao', nome: 'Aula de Violão', emoji: '🎸' },
    { id: 'aula_informatica', nome: 'Aula de Informática', emoji: '💻' },
    { id: 'aula_artes_marciais', nome: 'Artes Marciais', emoji: '🥋' },
  ],
  eventos: [
    { id: 'fotografo', nome: 'Fotógrafo', emoji: '📷' },
    { id: 'filmagem', nome: 'Filmagem', emoji: '🎬' },
    { id: 'dj', nome: 'DJ', emoji: '🎧' },
    { id: 'buffet', nome: 'Buffet', emoji: '🍽️' },
    { id: 'decorador', nome: 'Decorador de Eventos', emoji: '🎉' },
    { id: 'garcom', nome: 'Garçom e Barman', emoji: '🍷' },
    { id: 'animador', nome: 'Animador de Festas', emoji: '🎭' },
    { id: 'confeiteiro', nome: 'Confeiteiro e Bolo', emoji: '🎂' },
    { id: 'cerimonialista', nome: 'Cerimonialista', emoji: '💒' },
    { id: 'musico', nome: 'Músico e Banda', emoji: '🎵' },
  ],
  alimentacao: [
    { id: 'cozinheiro', nome: 'Cozinheiro Particular', emoji: '👨‍🍳' },
    { id: 'chef_domicilio', nome: 'Chef a Domicílio', emoji: '🍳' },
    { id: 'confeiteiro_ali', nome: 'Confeiteiro', emoji: '🍰' },
    { id: 'churrasqueiro', nome: 'Churrasqueiro', emoji: '🥩' },
    { id: 'salgadeiro', nome: 'Salgadeiro', emoji: '🥟' },
    { id: 'marmita', nome: 'Marmita e Quentinha', emoji: '🥡' },
    { id: 'bartender', nome: 'Bartender', emoji: '🍹' },
    { id: 'bolo_decorado', nome: 'Bolo Decorado', emoji: '🎂' },
    { id: 'pizzaiolo', nome: 'Pizzaiolo', emoji: '🍕' },
    { id: 'pao_artesanal', nome: 'Pão Artesanal', emoji: '🍞' },
  ],
  transporte: [
    { id: 'motorista', nome: 'Motorista Particular', emoji: '🚗' },
    { id: 'mudanca', nome: 'Mudança Residencial', emoji: '📦' },
    { id: 'frete', nome: 'Frete e Carreto', emoji: '🚛' },
    { id: 'mototaxista', nome: 'Mototaxista', emoji: '🏍️' },
    { id: 'entrega', nome: 'Entrega e Motoboy', emoji: '📦' },
    { id: 'motorista_executivo', nome: 'Motorista Executivo', emoji: '🚙' },
    { id: 'transporte_escolar', nome: 'Transporte Escolar', emoji: '🚌' },
    { id: 'carregador', nome: 'Carregador e Ajudante', emoji: '💪' },
    { id: 'guincho_auto', nome: 'Guincho Automotivo', emoji: '🚐' },
    { id: 'translado', nome: 'Translado e Transfer', emoji: '✈️' },
  ],
  seguranca: [
    { id: 'vigia', nome: 'Vigia e Segurança', emoji: '👮' },
    { id: 'chaveiro', nome: 'Chaveiro', emoji: '🔑' },
    { id: 'seguranca_evento', nome: 'Segurança para Eventos', emoji: '🦺' },
    { id: 'cftv_seguranca', nome: 'CFTV e Monitoramento', emoji: '📷' },
    { id: 'extintor', nome: 'Extintores e AVCB', emoji: '🧯' },
  ],
  animais: [
    { id: 'petisco', nome: 'Adestrador de Cães', emoji: '🐕' },
    { id: 'veterinario_domicilio', nome: 'Veterinário a Domicílio', emoji: '🐾' },
    { id: 'banho_tosa', nome: 'Banho e Tosa', emoji: '✂️' },
    { id: 'passeio_caes', nome: 'Passeio de Cães', emoji: '🦮' },
    { id: 'pet_sitter', nome: 'Pet Sitter', emoji: '🐱' },
    { id: 'transporte_pets', nome: 'Transporte de Pets', emoji: '🚗' },
    { id: 'fotografo_pets', nome: 'Fotógrafo de Pets', emoji: '📷' },
  ],
  juridico: [
    { id: 'advogado', nome: 'Advogado', emoji: '⚖️' },
    { id: 'contador', nome: 'Contador', emoji: '📊' },
    { id: 'consultor_financeiro', nome: 'Consultor Financeiro', emoji: '💰' },
    { id: 'despachante', nome: 'Despachante', emoji: '📋' },
    { id: 'corretor_imoveis', nome: 'Corretor de Imóveis', emoji: '🏠' },
    { id: 'tradutor', nome: 'Tradutor', emoji: '🌐' },
  ],
  design: [
    { id: 'arquiteto', nome: 'Arquiteto', emoji: '📐' },
    { id: 'designer_interiores', nome: 'Designer de Interiores', emoji: '🛋️' },
    { id: 'engenheiro_civil', nome: 'Engenheiro Civil', emoji: '🏗️' },
    { id: 'ilustrador', nome: 'Ilustrador', emoji: '✏️' },
    { id: 'redator', nome: 'Redator e Copywriter', emoji: '✍️' },
    { id: 'artesao', nome: 'Artesão', emoji: '🎭' },
    { id: 'vitrinista', nome: 'Vitrinista', emoji: '🏪' },
  ],
  moda: [
    { id: 'costureira', nome: 'Costureira', emoji: '🧵' },
    { id: 'alfaiate', nome: 'Alfaiate', emoji: '👔' },
    { id: 'ajuste_roupa', nome: 'Ajuste de Roupas', emoji: '✂️' },
    { id: 'sapateiro', nome: 'Sapateiro', emoji: '👞' },
    { id: 'personal_stylist', nome: 'Personal Stylist', emoji: '👗' },
    { id: 'customizacao', nome: 'Customização', emoji: '🎨' },
  ],
}

// Lista plana de todas as categorias
export const TODAS_CATEGORIAS = Object.entries(CATEGORIAS_POR_TOPICO).flatMap(([topico, cats]) =>
  cats.map(c => ({ ...c, topico_id: topico }))
)
