-- ============================================================
-- PRESTADOR — Taxonomia completa de tópicos e profissões
-- ============================================================
-- Importa os tópicos e categorias que já existiam localmente em
-- src/lib/dados.js mas nunca tinham sido levados pro banco (só 5
-- tópicos e 12 categorias estavam semeados). Usa "on conflict do
-- nothing" — não mexe em nada que já existe, só completa o resto.
-- Inclui também "Instalador de Acessórios Automotivos", categoria
-- nova sob o tópico Automotivo. Copie tudo e rode no SQL Editor.
-- ============================================================

-- Tópicos
insert into topicos (id, nome) values
  ('construcao', 'Construção e Reformas'),
  ('eletrica', 'Elétrica e Automação'),
  ('hidraulica', 'Hidráulica e Gás'),
  ('pintura', 'Pintura e Acabamento'),
  ('marcenaria', 'Marcenaria e Mobiliário'),
  ('limpeza', 'Limpeza e Conservação'),
  ('jardim', 'Jardim e Área Externa'),
  ('automotivo', 'Automotivo'),
  ('tecnologia', 'Tecnologia e TI'),
  ('saude', 'Saúde e Bem-estar'),
  ('beleza', 'Beleza e Estética'),
  ('educacao', 'Educação e Aulas'),
  ('eventos', 'Eventos e Entretenimento'),
  ('alimentacao', 'Alimentação e Culinária'),
  ('transporte', 'Transporte e Logística'),
  ('seguranca', 'Segurança'),
  ('animais', 'Pets e Animais'),
  ('juridico', 'Jurídico e Financeiro'),
  ('design', 'Design e Criação'),
  ('moda', 'Moda e Costura')
on conflict (id) do nothing;

-- Categorias
insert into categorias (id, nome, ordem) values
  ('pedreiro', 'Pedreiro', 100),
  ('mestre_obras', 'Mestre de Obras', 101),
  ('azulejista', 'Azulejista', 102),
  ('gesseiro', 'Gesseiro', 103),
  ('rebocador', 'Rebocador', 104),
  ('carpinteiro', 'Carpinteiro', 105),
  ('telhador', 'Telhador', 106),
  ('impermeabilizador', 'Impermeabilizador', 107),
  ('drywall', 'Drywall e Divisórias', 108),
  ('piscina', 'Piscinas', 109),
  ('madeira_deck', 'Deck de Madeira', 110),
  ('piso_vinilico', 'Piso Vinílico e Laminado', 111),
  ('cobertura', 'Coberturas e Pergolados', 112),
  ('porcelanato', 'Porcelanato', 113),
  ('concreto', 'Concretagem', 114),
  ('eletricista', 'Eletricista', 115),
  ('ar_condicionado', 'Ar-condicionado', 116),
  ('automacao', 'Automação Residencial', 117),
  ('cameras', 'Câmeras de Segurança', 118),
  ('painel_solar', 'Painel Solar', 119),
  ('alarme', 'Alarmes', 120),
  ('portao_eletrico', 'Portão Elétrico', 121),
  ('cerca_eletrica', 'Cerca Elétrica', 122),
  ('iluminacao', 'Iluminação e LED', 123),
  ('quadro_eletrico', 'Quadro Elétrico', 124),
  ('encanador', 'Encanador', 125),
  ('desentupidor', 'Desentupidor', 126),
  ('vazamento', 'Conserto de Vazamento', 127),
  ('aquecedor', 'Aquecedor e Boiler', 128),
  ('gas', 'Gás Natural e GLP', 129),
  ('fossa', 'Fossa e Esgoto', 130),
  ('caixa_agua', 'Caixa d''água', 131),
  ('bomba_agua', 'Bomba d''água', 132),
  ('banheiro_reforma', 'Reforma de Banheiro', 133),
  ('irrigacao', 'Irrigação', 134),
  ('pintor', 'Pintor', 135),
  ('textura', 'Textura e Grafiato', 136),
  ('gesso_decorativo', 'Gesso Decorativo', 137),
  ('papel_parede', 'Papel de Parede', 138),
  ('pintura_predial', 'Pintura Predial', 139),
  ('verniz', 'Verniz e Tingimento', 140),
  ('massa_corrida', 'Massa Corrida', 141),
  ('adesivo_decorativo', 'Adesivo Decorativo', 142),
  ('marceneiro', 'Marceneiro', 143),
  ('moveis_planejados', 'Móveis Planejados', 144),
  ('cozinha_planejada', 'Cozinha Planejada', 145),
  ('serralheiro', 'Serralheiro', 146),
  ('vidraceiro', 'Vidraceiro', 147),
  ('grades_ferro', 'Grades e Portões', 148),
  ('persiana', 'Persianas e Cortinas', 149),
  ('solda', 'Solda e Metalurgia', 150),
  ('closet', 'Closet Planejado', 151),
  ('box_banheiro', 'Box de Banheiro', 152),
  ('diarista', 'Diarista', 153),
  ('faxineira', 'Faxineira', 154),
  ('limpeza_pos_obra', 'Limpeza Pós-obra', 155),
  ('dedetizador', 'Dedetizador', 156),
  ('lavagem_sofa', 'Lavagem de Sofá', 157),
  ('lavagem_tapete', 'Lavagem de Tapete', 158),
  ('higienizacao_ar', 'Higienização de Ar', 159),
  ('limpeza_predial', 'Limpeza Predial', 160),
  ('sanitizacao', 'Sanitização', 161),
  ('controle_pragas', 'Controle de Pragas', 162),
  ('jardineiro', 'Jardineiro', 163),
  ('paisagista', 'Paisagista', 164),
  ('poda_arvore', 'Poda de Árvores', 165),
  ('corte_grama', 'Corte de Grama', 166),
  ('limpeza_terreno', 'Limpeza de Terreno', 167),
  ('grama_sintetica', 'Grama Sintética', 168),
  ('piscina_manutencao', 'Manutenção de Piscina', 169),
  ('mecanico', 'Mecânico', 170),
  ('funileiro', 'Funileiro', 171),
  ('eletrica_auto', 'Elétrica Automotiva', 172),
  ('polimento', 'Polimento e Vitrificação', 173),
  ('higienizacao_auto', 'Higienização Automotiva', 174),
  ('ar_auto', 'Ar-condicionado Auto', 175),
  ('guincho', 'Guincho e Reboque', 176),
  ('borracheiro', 'Borracheiro', 177),
  ('lavagem_auto', 'Lavagem Automotiva', 178),
  ('moto_mecanico', 'Mecânico de Motos', 179),
  ('tecnico_informatica', 'Técnico em Informática', 180),
  ('formatacao', 'Formatação e Manutenção', 181),
  ('desenvolvimento_web', 'Desenvolvimento Web', 182),
  ('design_grafico', 'Design Gráfico', 183),
  ('marketing_digital', 'Marketing Digital', 184),
  ('fotografia', 'Fotógrafo', 185),
  ('edicao_video', 'Edição de Vídeo', 186),
  ('drone', 'Drone e Fotografia Aérea', 187),
  ('social_media', 'Redes Sociais', 188),
  ('rede_internet', 'Rede e Internet', 189),
  ('personal_trainer', 'Personal Trainer', 190),
  ('nutricionista', 'Nutricionista', 191),
  ('fisioterapeuta', 'Fisioterapeuta', 192),
  ('massagista', 'Massagista', 193),
  ('enfermeiro', 'Enfermeiro Domiciliar', 194),
  ('cuidador_idoso', 'Cuidador de Idoso', 195),
  ('psicologo', 'Psicólogo', 196),
  ('pilates', 'Pilates', 197),
  ('yoga', 'Yoga e Meditação', 198),
  ('esteticista', 'Esteticista', 199),
  ('cabeleireiro', 'Cabeleireiro', 200),
  ('barbeiro', 'Barbeiro', 201),
  ('manicure', 'Manicure e Pedicure', 202),
  ('maquiadora', 'Maquiadora', 203),
  ('designer_sobrancelha', 'Designer de Sobrancelha', 204),
  ('micropigmentacao', 'Micropigmentação', 205),
  ('colorista', 'Colorista', 206),
  ('depilacao', 'Depilação', 207),
  ('nail_designer', 'Nail Designer', 208),
  ('limpeza_pele', 'Limpeza de Pele', 209),
  ('professor_particular', 'Professor Particular', 210),
  ('aula_ingles', 'Aula de Inglês', 211),
  ('aula_matematica', 'Aula de Matemática', 212),
  ('aula_musica', 'Aula de Música', 213),
  ('aula_danca', 'Aula de Dança', 214),
  ('reforco_escolar', 'Reforço Escolar', 215),
  ('personal_coach', 'Coaching e Mentoria', 216),
  ('aula_violao', 'Aula de Violão', 217),
  ('aula_informatica', 'Aula de Informática', 218),
  ('aula_artes_marciais', 'Artes Marciais', 219),
  ('fotografo', 'Fotógrafo', 220),
  ('filmagem', 'Filmagem', 221),
  ('dj', 'DJ', 222),
  ('buffet', 'Buffet', 223),
  ('decorador', 'Decorador de Eventos', 224),
  ('garcom', 'Garçom e Barman', 225),
  ('animador', 'Animador de Festas', 226),
  ('confeiteiro', 'Confeiteiro e Bolo', 227),
  ('cerimonialista', 'Cerimonialista', 228),
  ('musico', 'Músico e Banda', 229),
  ('cozinheiro', 'Cozinheiro Particular', 230),
  ('chef_domicilio', 'Chef a Domicílio', 231),
  ('confeiteiro_ali', 'Confeiteiro', 232),
  ('churrasqueiro', 'Churrasqueiro', 233),
  ('salgadeiro', 'Salgadeiro', 234),
  ('marmita', 'Marmita e Quentinha', 235),
  ('bartender', 'Bartender', 236),
  ('bolo_decorado', 'Bolo Decorado', 237),
  ('pizzaiolo', 'Pizzaiolo', 238),
  ('pao_artesanal', 'Pão Artesanal', 239),
  ('motorista', 'Motorista Particular', 240),
  ('mudanca', 'Mudança Residencial', 241),
  ('frete', 'Frete e Carreto', 242),
  ('mototaxista', 'Mototaxista', 243),
  ('entrega', 'Entrega e Motoboy', 244),
  ('motorista_executivo', 'Motorista Executivo', 245),
  ('transporte_escolar', 'Transporte Escolar', 246),
  ('carregador', 'Carregador e Ajudante', 247),
  ('guincho_auto', 'Guincho Automotivo', 248),
  ('translado', 'Translado e Transfer', 249),
  ('vigia', 'Vigia e Segurança', 250),
  ('chaveiro', 'Chaveiro', 251),
  ('seguranca_evento', 'Segurança para Eventos', 252),
  ('cftv_seguranca', 'CFTV e Monitoramento', 253),
  ('extintor', 'Extintores e AVCB', 254),
  ('petisco', 'Adestrador de Cães', 255),
  ('veterinario_domicilio', 'Veterinário a Domicílio', 256),
  ('banho_tosa', 'Banho e Tosa', 257),
  ('passeio_caes', 'Passeio de Cães', 258),
  ('pet_sitter', 'Pet Sitter', 259),
  ('transporte_pets', 'Transporte de Pets', 260),
  ('fotografo_pets', 'Fotógrafo de Pets', 261),
  ('advogado', 'Advogado', 262),
  ('contador', 'Contador', 263),
  ('consultor_financeiro', 'Consultor Financeiro', 264),
  ('despachante', 'Despachante', 265),
  ('corretor_imoveis', 'Corretor de Imóveis', 266),
  ('tradutor', 'Tradutor', 267),
  ('arquiteto', 'Arquiteto', 268),
  ('designer_interiores', 'Designer de Interiores', 269),
  ('engenheiro_civil', 'Engenheiro Civil', 270),
  ('ilustrador', 'Ilustrador', 271),
  ('redator', 'Redator e Copywriter', 272),
  ('artesao', 'Artesão', 273),
  ('vitrinista', 'Vitrinista', 274),
  ('costureira', 'Costureira', 275),
  ('alfaiate', 'Alfaiate', 276),
  ('ajuste_roupa', 'Ajuste de Roupas', 277),
  ('sapateiro', 'Sapateiro', 278),
  ('personal_stylist', 'Personal Stylist', 279),
  ('customizacao', 'Customização', 280),
  ('instalador_acessorios_auto', 'Instalador de Acessórios Automotivos', 281)
on conflict (id) do nothing;

-- Vínculos tópico ⇄ categoria
insert into topico_categorias (topico_id, categoria_id) values
  ('construcao', 'pedreiro'),
  ('construcao', 'mestre_obras'),
  ('construcao', 'azulejista'),
  ('construcao', 'gesseiro'),
  ('construcao', 'rebocador'),
  ('construcao', 'carpinteiro'),
  ('construcao', 'telhador'),
  ('construcao', 'impermeabilizador'),
  ('construcao', 'drywall'),
  ('construcao', 'piscina'),
  ('construcao', 'madeira_deck'),
  ('construcao', 'piso_vinilico'),
  ('construcao', 'cobertura'),
  ('construcao', 'porcelanato'),
  ('construcao', 'concreto'),
  ('eletrica', 'eletricista'),
  ('eletrica', 'ar_condicionado'),
  ('eletrica', 'automacao'),
  ('eletrica', 'cameras'),
  ('eletrica', 'painel_solar'),
  ('eletrica', 'alarme'),
  ('eletrica', 'portao_eletrico'),
  ('eletrica', 'cerca_eletrica'),
  ('eletrica', 'iluminacao'),
  ('eletrica', 'quadro_eletrico'),
  ('hidraulica', 'encanador'),
  ('hidraulica', 'desentupidor'),
  ('hidraulica', 'vazamento'),
  ('hidraulica', 'aquecedor'),
  ('hidraulica', 'gas'),
  ('hidraulica', 'fossa'),
  ('hidraulica', 'caixa_agua'),
  ('hidraulica', 'bomba_agua'),
  ('hidraulica', 'banheiro_reforma'),
  ('hidraulica', 'irrigacao'),
  ('pintura', 'pintor'),
  ('pintura', 'textura'),
  ('pintura', 'gesso_decorativo'),
  ('pintura', 'papel_parede'),
  ('pintura', 'pintura_predial'),
  ('pintura', 'verniz'),
  ('pintura', 'massa_corrida'),
  ('pintura', 'adesivo_decorativo'),
  ('marcenaria', 'marceneiro'),
  ('marcenaria', 'moveis_planejados'),
  ('marcenaria', 'cozinha_planejada'),
  ('marcenaria', 'serralheiro'),
  ('marcenaria', 'vidraceiro'),
  ('marcenaria', 'grades_ferro'),
  ('marcenaria', 'persiana'),
  ('marcenaria', 'solda'),
  ('marcenaria', 'closet'),
  ('marcenaria', 'box_banheiro'),
  ('limpeza', 'diarista'),
  ('limpeza', 'faxineira'),
  ('limpeza', 'limpeza_pos_obra'),
  ('limpeza', 'dedetizador'),
  ('limpeza', 'lavagem_sofa'),
  ('limpeza', 'lavagem_tapete'),
  ('limpeza', 'higienizacao_ar'),
  ('limpeza', 'limpeza_predial'),
  ('limpeza', 'sanitizacao'),
  ('limpeza', 'controle_pragas'),
  ('jardim', 'jardineiro'),
  ('jardim', 'paisagista'),
  ('jardim', 'poda_arvore'),
  ('jardim', 'corte_grama'),
  ('jardim', 'limpeza_terreno'),
  ('jardim', 'grama_sintetica'),
  ('jardim', 'piscina_manutencao'),
  ('automotivo', 'mecanico'),
  ('automotivo', 'funileiro'),
  ('automotivo', 'eletrica_auto'),
  ('automotivo', 'polimento'),
  ('automotivo', 'higienizacao_auto'),
  ('automotivo', 'ar_auto'),
  ('automotivo', 'guincho'),
  ('automotivo', 'borracheiro'),
  ('automotivo', 'lavagem_auto'),
  ('automotivo', 'moto_mecanico'),
  ('tecnologia', 'tecnico_informatica'),
  ('tecnologia', 'formatacao'),
  ('tecnologia', 'desenvolvimento_web'),
  ('tecnologia', 'design_grafico'),
  ('tecnologia', 'marketing_digital'),
  ('tecnologia', 'fotografia'),
  ('tecnologia', 'edicao_video'),
  ('tecnologia', 'drone'),
  ('tecnologia', 'social_media'),
  ('tecnologia', 'rede_internet'),
  ('saude', 'personal_trainer'),
  ('saude', 'nutricionista'),
  ('saude', 'fisioterapeuta'),
  ('saude', 'massagista'),
  ('saude', 'enfermeiro'),
  ('saude', 'cuidador_idoso'),
  ('saude', 'psicologo'),
  ('saude', 'pilates'),
  ('saude', 'yoga'),
  ('saude', 'esteticista'),
  ('beleza', 'cabeleireiro'),
  ('beleza', 'barbeiro'),
  ('beleza', 'manicure'),
  ('beleza', 'maquiadora'),
  ('beleza', 'designer_sobrancelha'),
  ('beleza', 'micropigmentacao'),
  ('beleza', 'colorista'),
  ('beleza', 'depilacao'),
  ('beleza', 'nail_designer'),
  ('beleza', 'limpeza_pele'),
  ('educacao', 'professor_particular'),
  ('educacao', 'aula_ingles'),
  ('educacao', 'aula_matematica'),
  ('educacao', 'aula_musica'),
  ('educacao', 'aula_danca'),
  ('educacao', 'reforco_escolar'),
  ('educacao', 'personal_coach'),
  ('educacao', 'aula_violao'),
  ('educacao', 'aula_informatica'),
  ('educacao', 'aula_artes_marciais'),
  ('eventos', 'fotografo'),
  ('eventos', 'filmagem'),
  ('eventos', 'dj'),
  ('eventos', 'buffet'),
  ('eventos', 'decorador'),
  ('eventos', 'garcom'),
  ('eventos', 'animador'),
  ('eventos', 'confeiteiro'),
  ('eventos', 'cerimonialista'),
  ('eventos', 'musico'),
  ('alimentacao', 'cozinheiro'),
  ('alimentacao', 'chef_domicilio'),
  ('alimentacao', 'confeiteiro_ali'),
  ('alimentacao', 'churrasqueiro'),
  ('alimentacao', 'salgadeiro'),
  ('alimentacao', 'marmita'),
  ('alimentacao', 'bartender'),
  ('alimentacao', 'bolo_decorado'),
  ('alimentacao', 'pizzaiolo'),
  ('alimentacao', 'pao_artesanal'),
  ('transporte', 'motorista'),
  ('transporte', 'mudanca'),
  ('transporte', 'frete'),
  ('transporte', 'mototaxista'),
  ('transporte', 'entrega'),
  ('transporte', 'motorista_executivo'),
  ('transporte', 'transporte_escolar'),
  ('transporte', 'carregador'),
  ('transporte', 'guincho_auto'),
  ('transporte', 'translado'),
  ('seguranca', 'vigia'),
  ('seguranca', 'chaveiro'),
  ('seguranca', 'seguranca_evento'),
  ('seguranca', 'cftv_seguranca'),
  ('seguranca', 'extintor'),
  ('animais', 'petisco'),
  ('animais', 'veterinario_domicilio'),
  ('animais', 'banho_tosa'),
  ('animais', 'passeio_caes'),
  ('animais', 'pet_sitter'),
  ('animais', 'transporte_pets'),
  ('animais', 'fotografo_pets'),
  ('juridico', 'advogado'),
  ('juridico', 'contador'),
  ('juridico', 'consultor_financeiro'),
  ('juridico', 'despachante'),
  ('juridico', 'corretor_imoveis'),
  ('juridico', 'tradutor'),
  ('design', 'arquiteto'),
  ('design', 'designer_interiores'),
  ('design', 'engenheiro_civil'),
  ('design', 'ilustrador'),
  ('design', 'redator'),
  ('design', 'artesao'),
  ('design', 'vitrinista'),
  ('moda', 'costureira'),
  ('moda', 'alfaiate'),
  ('moda', 'ajuste_roupa'),
  ('moda', 'sapateiro'),
  ('moda', 'personal_stylist'),
  ('moda', 'customizacao'),
  ('automotivo', 'instalador_acessorios_auto')
on conflict (topico_id, categoria_id) do nothing;

